#! /usr/bin/fish

set weekstamp (date +%Y-v%W-%u-%A-%H.%M.%S)

cd /
pacman -Q > pacQ.lst
pacman -Qm > pacQm.lst
pacman -Qqe > pacQqe.lst
mount /dev/sda3 /mnt
cd /mnt/\@manjaro
rsync -a --del /boot/ \@/boot/
btrfs subvolume snapshot -r \@home \@home.$weekstamp
btrfs subvolume snapshot -r \@ \@root.$weekstamp
cd
umount /mnt
