#! /usr/bin/fish

set weekstamp (date +%Y-v%V-%u-%a-%H.%M.%S)

if set -q argv[1]
for snap in $argv
    set snap (string trim -rc / $snap)
    btrfs subvolume snapshot -r $snap $snap.$weekstamp
end
else

cd /
pacman -Q > pacQ.lst
pacman -Qm > pacQm.lst
pacman -Qqe > pacQqe.lst
mount -U 6254e738-c2f9-4224-bd7c-8926721470c0 /mnt
cd /mnt/
rsync -a --del /boot/ \@boot/
for snap in @root @var @boot @home
    btrfs subvolume snapshot -r $snap $snap.$weekstamp
end

cd
umount /mnt

end
