#! /usr/bin/fish

set weekstamp (date +%Y-v%W-%u-%a-%H.%M.%S)

cd /
pacman -Q > pacQ.lst
pacman -Qm > pacQm.lst
pacman -Qqe > pacQqe.lst
mount /dev/sda3 /mnt
cd /mnt/\@manjaro
rsync -a --del /boot/ \@boot/
for snap in @root @var @boot @home
    btrfs subvolume snapshot -r $snap $snap.$weekstamp
end
cd
umount /mnt
